DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'lab' AND table_name = 'test_projects' AND column_name = 'id'
      AND (identity_generation IS NULL OR identity_generation = '')
      AND column_default IS NULL
  ) THEN
    ALTER TABLE lab.test_projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'lab' AND table_name = 'sample_measurements' AND column_name = 'id'
      AND (identity_generation IS NULL OR identity_generation = '')
      AND column_default IS NULL
  ) THEN
    ALTER TABLE lab.sample_measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('lab.test_projects', 'id'),
  COALESCE((SELECT max(id) FROM lab.test_projects), 1),
  EXISTS (SELECT 1 FROM lab.test_projects)
);

SELECT setval(
  pg_get_serial_sequence('lab.sample_measurements', 'id'),
  COALESCE((SELECT max(id) FROM lab.sample_measurements), 1),
  EXISTS (SELECT 1 FROM lab.sample_measurements)
);