from __future__ import annotations

from pathlib import Path
import tempfile
import unittest

from scripts.ci import validate_dependency_locks as policy


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]


class DependencyLockPolicyTests(unittest.TestCase):
    def test_repository_dependency_policy(self) -> None:
        self.assertEqual(policy.validate(REPOSITORY_ROOT), [])

    def test_requirement_without_hash_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            lock = Path(raw) / "requirements.lock"
            lock.write_text("example==1.2.3\n", encoding="utf-8")
            self.assertIn("has no SHA256 hash", "\n".join(policy.validate_lock_hashes(lock)))

    def test_input_cannot_include_an_unreviewed_requirement_file(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            requirements = Path(raw) / "requirements.in"
            requirements.write_text("-r unreviewed.txt\nexample==1.2.3\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "directives are not allowed"):
                policy.input_versions(requirements)

    def test_system_lock_hash_is_exact(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            backend = root / "backend"
            backend.mkdir()
            (backend / "requirements-system.in").write_text(
                "torch==2.9.1+cu128\ntorchvision==0.24.1+cu128\n",
                encoding="utf-8",
            )
            (backend / "requirements-system.lock").write_text(
                "torch==2.9.1+cu128 \\\n"
                "    --hash=sha256:" + "0" * 64 + "\n"
                "torchvision==0.24.1+cu128 \\\n"
                "    --hash=sha256:" + policy.SYSTEM_HASHES["torchvision"] + "\n",
                encoding="utf-8",
            )
            self.assertIn("reviewed CPython 3.11 Linux wheel hash", "\n".join(policy.validate_system_lock(root)))

    def test_backend_split_rejects_legacy_cuda_packages(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            backend = root / "backend"
            backend.mkdir()
            (backend / "requirements-runtime.in").write_text("example==1.0\n", encoding="utf-8")
            (backend / "requirements.lock").write_text(
                "# generated by pip-compile\n"
                "example==1.0\n"
                "scikit-learn==1.8.0\n"
                "transformers==4.57.6\n"
                "nvidia-cublas-cu11==11.11.3.6\n",
                encoding="utf-8",
            )

            failures = policy.validate_backend_split(root)

            self.assertIn("CUDA 11 packages must not be mixed", "\n".join(failures))

    def test_cuda_12_base_runtime_includes_split_cuda_packages(self) -> None:
        self.assertIn("nvidia-cusparselt-cu12", policy.BASE_RUNTIME_PACKAGES)
        self.assertIn("nvidia-nvjitlink-cu12", policy.BASE_RUNTIME_PACKAGES)
        self.assertIn("nvidia-cufile-cu12", policy.BASE_RUNTIME_PACKAGES)
        self.assertIn("nvidia-nvshmem-cu12", policy.BASE_RUNTIME_PACKAGES)


if __name__ == "__main__":
    unittest.main()
